force-app/main/default/objects/Response_Attribute__c/Response_Attribute__c.object-meta.xml
<CustomObject>
    <label>Response Attribute</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Response Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Attribute__c/fields/Response_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Response_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Response Configuration</label>
    <referenceTo>Response_Configuration__c</referenceTo>
    <relationshipLabel>Response Attributes</relationshipLabel>
    <relationshipName>Response_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response_Configuration__c/Response_Configuration__c.object-meta.xml
<CustomObject>
    <label>Response Configuration</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>Response Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AbstractResponser.cls
public abstract class AbstractResponser {
    protected Map<Integer, List<Id>> levelDigitMap;
    protected Map<Id, List<Response_Attribute__c>> objectAttributeMap;
    protected List<Integer> sortedLevelsList;
    protected Response_Configuration__c responseConfiguration;
    
    /* *********************************************
    ** Method Name: AbstractResponser
    ** Parameters: no
    ** Returns: void
    ** ********************************************* */
    public AbstractResponser() {
        objectAttributeMap 	= new Map<Id, List<Response_Attribute__c>>();
        levelDigitMap 		= new Map<Integer, List<Id>>();
        sortedLevelsList	= new List<Integer>();
    }
    public void setResponseConfiguration(Response_Configuration__c responseConfiguration) {
        this.responseConfiguration = responseConfiguration;
    }
    public abstract String main();
}