force-app/main/default/objects/Response_Attribute__c/Response_Attribute__c.object-meta.xml
<CustomObject>
    <label>Response Attribute</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Response Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Attribute__c/fields/Response_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Response_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Response Configuration</label>
    <referenceTo>Response_Configuration__c</referenceTo>
    <relationshipLabel>Response Attributes</relationshipLabel>
    <relationshipName>Response_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response_Attribute__c/fields/Response_Object__c.field-meta.xml
<CustomField>
    <fullName>Response_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Response Object</label>
    <referenceTo>Response_Object__c</referenceTo>
    <relationshipLabel>Response Attributes</relationshipLabel>
    <relationshipName>Response_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response_Attribute__c/fields/Tag_Name__c.field-meta.xml
<CustomField>
    <fullName>Tag_Name__c</fullName>
    <label>Tag Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Response_Configuration__c/Response_Configuration__c.object-meta.xml
<CustomObject>
    <label>Response Configuration</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>Response Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Object__c/Response_Object__c.object-meta.xml
<CustomObject>
    <label>Response Object</label>
    <nameField>
        <label>Response Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Response Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Object__c/fields/Response_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Response_Configuration__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Response Configuration</label>
    <referenceTo>Response_Configuration__c</referenceTo>
    <relationshipLabel>Response Objects</relationshipLabel>
    <relationshipName>Response_Objects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response_Object__c/fields/Response_Object__c.field-meta.xml
<CustomField>
    <fullName>Response_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Response Object</label>
    <referenceTo>Response_Object__c</referenceTo>
    <relationshipLabel>Response Objects</relationshipLabel>
    <relationshipName>Response_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ConfiguredResponser.cls
public class ConfiguredResponser extends AbstractResponser {
    private Map<Id, Response_Object__c> responseObjectMap;
    private Map<Id, Response_Attribute__c> responseAttributesMap;
    private Set<Integer> sortedLevelsSet;
    private Boolean sortNeeded = false;
    private String responseText;
    private String resourceId;
    
    public void setSortable(Boolean sortNeeded) {
        this.sortNeeded = sortNeeded;
    }
    
   /* *********************************************
    ** Method Name: main
    ** Parameters: no
    ** Returns: String, returns JSON
    ** ********************************************* */
    public override String main() {
        queryResponseConfiguration(resourceId);
        queryResponseObjects(resourceId);
        queryResponseAttributes(resourceId);
        //setSortable(true);
        buildLevelMap();
        //arrangeLevels();
        return buildJSON();
    }
    
    private void queryResponseConfiguration(String resourceId) {
        responseConfiguration = [SELECT Id, RecordTypeId FROM Response_Configuration__c WHERE Id = :resourceId];    
        if (responseConfiguration == null) {
            throw new SObjectException('No configuration');
        } 
    }
    private void queryResponseObjects(String resourceId) {
        responseObjectMap = new Map<Id, Response_Object__c>([SELECT Id, Name, Response_Configuration__c, Response_Object__c  
                                                             FROM Response_Object__c WHERE Response_Configuration__c = :resourceId]);
        if (responseObjectMap == null || responseObjectMap.isEmpty()) {
            throw new SObjectException('No objects');
        }
    }
    private void queryResponseAttributes(String resourceId) {
        responseAttributesMap = new Map<Id, Response_Attribute__c>([SELECT Id, Response_Object__c, Response_Configuration__c, Tag_Name__c, Value__c 
                                                                    FROM Response_Attribute__c WHERE Response_Configuration__c = :resourceId]);
    }
    public ConfiguredResponser(String resourceId) {
        super();
        this.resourceId = resourceId;
    }
    
	/* *********************************************
	** Method Name: buildLevelMap
	** Description: builds map of level vs node id
	** Parameters: no
	** Returns: void
	** ********************************************* */
    private void buildLevelMap() {
        for (Id attributeKey : responseAttributesMap.keySet()) {
            Response_Attribute__c attribute = responseAttributesMap.get(attributeKey);
            if (objectAttributeMap.containsKey(attribute.Response_Object__c)) {
                objectAttributeMap.get(attribute.Response_Object__c).add(attribute);
            } else {
                objectAttributeMap.put(
                    attribute.Response_Object__c,
                    new List<Response_Attribute__c>{attribute}
                );
            }
        }
        
        Boolean topLevelFound = false;
        while (responseObjectMap.size() > 0) {
            System.debug('SIZE: ' + responseObjectMap.size());

            for (Id responseKey : responseObjectMap.keySet()) {
                Response_Object__c responseNode = responseObjectMap.get(responseKey);
                
                if (responseNode.Response_Object__c == null) {
                    this.levelDigitMap.put(0, new List<Id>{responseKey});
                    this.sortedLevelsList.add(0);
                    
                    topLevelFound = true;
                    responseObjectMap.remove(responseKey);
                    break;
                } else if (topLevelFound) {
                    Integer level = getParentLevel(this.levelDigitMap, responseNode.Response_Object__c);
                    if (this.levelDigitMap.get(level + 1) != null) {
                        this.levelDigitMap.get(level + 1).add(responseKey);
                    } else {
                        this.levelDigitMap.put(level + 1, new List<Id>{responseKey});
                    }
                    this.sortedLevelsList.add(level + 1);
                    responseObjectMap.remove(responseKey);
                    continue;                        
                }
            }   
        }     
        System.debug(this.levelDigitMap);
    }
    
    /* *********************************************
	** Method Name: buildJSON
	** Description: builds JSON based on level map
	** Parameters: 
	** Returns: String
	** ********************************************* */
    private String buildJSON() {
        JSONGenerator gen = JSON.createGenerator(true);
        
        gen.writeStartObject();
        for (Integer level = 0; level < this.levelDigitMap.keySet().size(); level++) {
            if (this.levelDigitMap.containsKey(level)) {
                List<Id> nodes = this.levelDigitMap.get(level);

                if (level == 0) {
                    for (Id attribute : responseAttributesMap.keySet()) {
                        if (responseAttributesMap.get(attribute).Response_Object__c == nodes[0]) {
                            gen.writeStringField(
                                responseAttributesMap.get(attribute).Tag_Name__c, 
                                responseAttributesMap.get(attribute).Value__c
                            );
                        }
                    }
                } else {
                    
                }
            }
        }
        gen.writeEndObject();
        
        return gen.getAsString();
    }
    
	/* *********************************************
	** Method Name: getParentLevel
	** Description: 
	** Parameters: Map<Integer, Set<Id>> - current level map, Id - 
	** Returns: Integer
	** ********************************************* */
    private Integer getParentLevel(Map<Integer, List<Id>> levelDigitMap, Id parentNodeId) {
        for (Integer level : levelDigitMap.keySet()) {
            if (levelDigitMap.get(level).contains(parentNodeId)) {
                return level;
            }
        }  
        return -1;
    }
    
    /* *********************************************
	** Method Name: arrangeLevels
	** Description: 
	** Parameters: no
	** Returns: void
	** ********************************************* */
    private void arrangeLevels() {
        if (this.sortNeeded) {
            sortedLevelsList.sort();
            sortedLevelsSet = new Set<Integer>();
            for (Integer level : sortedLevelsList) {
                sortedLevelsSet.add(level);
            } 
        } else {
            for (Integer level : this.levelDigitMap.keySet()) {
                sortedLevelsSet.add(level);
            }
        }
    }
}