force-app/main/default/objects/Response_Configuration__c/Response_Configuration__c.object-meta.xml
<CustomObject>
    <label>Response Configuration</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>Response Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Configuration__c/fields/Raw_Response__c.field-meta.xml
<CustomField>
    <fullName>Raw_Response__c</fullName>
    <label>Raw Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Response_Configuration__c/recordTypes/Configurable.recordType-meta.xml
<RecordType>
    <fullName>Configurable</fullName>
    <active>true</active>
    <label>Configurable</label>
</RecordType>

force-app/main/default/objects/Response_Configuration__c/recordTypes/Raw.recordType-meta.xml
<RecordType>
    <fullName>Raw</fullName>
    <active>true</active>
    <label>Raw</label>
</RecordType>

force-app/main/default/classes/ResponseFactory.cls
public class ResponseFactory {
	public static Id RECORDTYPE_CONFIGURABLE    = Schema.SObjectType.Response_Configuration__c.getRecordTypeInfosByName().get('Configurable').getRecordTypeId();
	public static Id RECORDTYPE_RAW             = Schema.SObjectType.Response_Configuration__c.getRecordTypeInfosByName().get('Raw').getRecordTypeId();
    public static String MIRROR_STRING          = 'mirror';
    public static String MIRROR_HEADERS_STRING  = 'mirror-headers';
    
   	public static Response_Configuration__c queryResponseConfiguration(String resourceId) {
        return [SELECT Id, RecordTypeId, Raw_Response__c FROM Response_Configuration__c WHERE Id = :resourceId];    
    }
    
    public AbstractResponser getResponseByType(String resourceId) {
        if (resourceId.equals(MIRROR_STRING)) {
            return new MirrorResponser();
        } else if (resourceId.equals(MIRROR_HEADERS_STRING)) {
            return new MirrorHeadersResponser();
        } else {
            return returnNonStaticResponse(resourceId);
        }
    }
    
    private AbstractResponser returnNonStaticResponse(String resourceId) {
        AbstractResponser responser;
        Response_Configuration__c configuration = queryResponseConfiguration(resourceId);
        Id responseRecordTypeId = configuration.RecordTypeId;
        
        if (responseRecordTypeId == RECORDTYPE_RAW) {
            responser = new RawResponser(resourceId);
        } else if (responseRecordTypeId == RECORDTYPE_CONFIGURABLE) {
            responser = new ConfiguredResponser(resourceId);
        }
        responser.setResponseConfiguration(configuration);
        return responser;
    }
}